### ISSUE TITLE
SystRankingPlot *** Break *** segmentation violation

### ISSUE THREAD

**Issue by luilongo** [histfitter/histfitter#135]
I observe a segmentation violation, while trying to run SystRankingPlot.py or SystRankingPlotMP.py (both from HF master). 
Output error of SystRankingPlot.py  is 
```
Traceback (most recent call last):
  File "/afs/cern.ch/user/l/llongo/work/SUSY/HistFitterShift/histfitter/scripts/SystRankingPlot.py", line 480, in <module>
    main()
  File "/afs/cern.ch/user/l/llongo/work/SUSY/HistFitterShift/histfitter/scripts/SystRankingPlot.py", line 460, in main
    ranking, stat_only = get_syst_ranking(opts)
  File "/afs/cern.ch/user/l/llongo/work/SUSY/HistFitterShift/histfitter/scripts/SystRankingPlot.py", line 105, in get_syst_ranking
    fit_result = refit_fixed(name + "_fixed", par_name, value, w, fit_regions, data_set)
  File "/afs/cern.ch/user/l/llongo/work/SUSY/HistFitterShift/histfitter/scripts/SystRankingPlot.py", line 40, in refit_fixed
    fit_result = Util.FitPdf(w, fit_regions, True, data_set, fit_name, True, "all")
cppyy.ll.SegmentationViolation: RooFitResult* Util::FitPdf(RooWorkspace* w, TString fitRegions = "ALL", bool lumiConst = false, RooAbsData* inputData = 0, TString suffix = "", bool minos = kFALSE, TString minosPars = "", bool doFixParameters = kFALSE, TString fixedPars = "") =>
    SegmentationViolation: segfault in C++; program state was reset
```
    while for SystRankingPlotMP.py is
```
    RooAbsTestStatistic::initSimMode: creating slave calculator #0 for state QCDCR_cuts (1 dataset entries)
 *** Break *** segmentation violation
input_line_231:4:7: error: redefinition of 'cppyy_cast'
    T cppyy_cast(U val) { return (T)val; }
      ^
input_line_153:4:7: note: previous definition is here
    T cppyy_cast(U val) { return (T)val; }
      ^
input_line_231:7:7: error: redefinition of 'cppyy_static_cast'
    T cppyy_static_cast(U val) { return static_cast<T>(val); }
      ^
input_line_153:7:7: note: previous definition is here
    T cppyy_static_cast(U val) { return static_cast<T>(val); }
      ^
input_line_231:10:7: error: redefinition of 'cppyy_reinterpret_cast'
    T cppyy_reinterpret_cast(U val) { return reinterpret_cast<T>(val); }
      ^
input_line_153:10:7: note: previous definition is here
    T cppyy_reinterpret_cast(U val) { return reinterpret_cast<T>(val); }
      ^
input_line_231:13:8: error: redefinition of 'cppyy_dynamic_cast'
    T* cppyy_dynamic_cast(S* obj) { return dynamic_cast<T*>(obj); }
       ^
input_line_153:13:8: note: previous definition is here
    T* cppyy_dynamic_cast(S* obj) { return dynamic_cast<T*>(obj); }
       ^
input_line_231:20:8: error: redefinition of 'cppyy_array_new'
    T* cppyy_array_new(size_t count) { return new T[count]; }
       ^
input_line_153:20:8: note: previous definition is here
    T* cppyy_array_new(size_t count) { return new T[count]; }
       ^
input_line_231:23:10: error: redefinition of 'cppyy_array_delete'
    void cppyy_array_delete(T* ptr) { delete[] ptr; }
         ^
input_line_153:23:10: note: previous definition is here
    void cppyy_array_delete(T* ptr) { delete[] ptr; }
         ^
```
 
The root version used is 
```
ROOT Version: 6.22/00
Built for linuxx8664gcc on Jun 14 2020, 15:54:05
From tags/v6-22-00@v6-22-00
```
with Python 3.7.6

**Comment by longjon929** [comment]
Hi @luilongo ,

Thanks, how are you running it?  I have ROOT 6.24/00 + Python 3.8.6 setup and see what looks like a python type error with:
SystRankingPlot.py -w results/MyUserAnalysis/SPlusB_combined_NormalMeasurement_model_afterFit.root -f UserRegion -p mu_Sig

```
Traceback (most recent call last):
  File "/afs/cern.ch/user/l/longjon/work/HistFitter_github/scripts/SystRankingPlot.py", line 480, in <module>
    main()
  File "/afs/cern.ch/user/l/longjon/work/HistFitter_github/scripts/SystRankingPlot.py", line 466, in main
    pickle.dump((ranking, stat_only), pfile)
TypeError: write() argument must be str, not bytes
```

**Comment by luilongo** [comment]
Hi @longjon929 thanks! I've still the same problem with my old root and  python versions. I'll give it a try in the next days.

**Comment by luilongo** [comment]
The problem is not anymore there. Thanks @longjon929
