### ISSUE TITLE
SysTable.py handling regions where there are samples which have zero yields

### ISSUE THREAD

**Issue by kratsg** [histfitter/histfitter#22]
In GitLab by @clmalone on May 28, 2021, 08:35

Hi

When running SysTable.py on my local machine with this command

SysTable.py  -m 1 -% -b -w /usera/cnbm2/HistFitter_compressed_release21/HistFitter62/results/THEORY_TTBAR_THEORY_WJET_LSR_claire_ntuples/Template_BkgOnly_combined_NormalMeasurement_model_afterFit.root -c LSR,TSR,SRB0,TCR,WCR,TVR,WVR -o Claires_SysTables/tWZ_allchannels_before_test.tex -s tWZ

I encountered the following error 

RooFit v3.60 -- Developed by Wouter Verkerke and David Kirkby 
                Copyright (C) 2000-2013 NIKHEF, University of California & Stanford University
                All rights reserved, please read http://roofit.sourceforge.net/license.txt

cnbm2 in the else chosensample method 1
cnbm2, filename = /usera/cnbm2/HistFitter_compressed_release21/HistFitter62/results/THEORY_TTBAR_THEORY_WJET_LSR_claire_ntuples/Template_BkgOnly_combined_NormalMeasurement_model_afterFit.root

  Table channelCat : obsData
  +----------+------+
  | LSR_cuts | 1.5223 |
  | TCR_cuts | 1186 |
  | TVR_cuts |  158 |
  | WCR_cuts | 2534 |
  | WVR_cuts |  732 |
  +----------+------+

CNBM2 chosen sample =  True
CNBM2 regionCatStr =  channelCat==channelCat::LSR_cuts
CNBM2 nobsRegion =  1.5223031044 dataRegion =  <ROOT.RooDataSet object ("obsData") at 0x66f3184>
CNBM2 regSys =  {'sqrtnobsa': 0.0}
<ERROR> Util:  Something wrong with compFuncList or compCoefList in Util::GetComponent(w,tWZ,LSR) 
<ERROR> Util:          compFuncList.getSize() = 0 compCoefList.getSize() = 0
 
 Warning, could not find pdf in region =  LSR  for sample =  tWZ
Traceback (most recent call last):
  File "/usera/cnbm2/HistFitter_compressed_release21/HistFitter62/scripts/SysTable.py", line 1096, in <module>
    regSys = latexfitresults(wsFileName,namemap,chan,sample,resultName,'obsData',doAsym) 
  File "/usera/cnbm2/HistFitter_compressed_release21/HistFitter62/scripts/SysTable.py", line 168, in latexfitresults
    nFittedInRegion=pdfInRegion.getVal()
TypeError: none of the 2 overloaded methods succeeded. Full details:
  attempt to access a null-pointer
  double RooAbsReal::getVal(const RooArgSet& set) =>
    takes at least 1 arguments (0 given)

This occurs when the -s option is used because the sample (tWZ) has zero events in the region LSR. I have copied my workspace to 

/afs/cern.ch/user/c/clmalone/public/histfitter_workspace

Please can the SysTable.py script be developed so that this error can be avoided and a systematic table is produced even if one of the regions contains zero events?

Best wishes - Claire

**Comment by kratsg** [comment]
In GitLab by @llongo on May 30, 2021, 17:27

Dear Claire,
I've included a fix to this issue in the merge request [75](https://gitlab.cern.ch/HistFitter/HistFitter/-/merge_requests/75). Let me know in case there will be still a problem.
Cheers, 
Luigi
