### ISSUE TITLE
Option in multiplexContours.py to produce a plot of best expected contours - [merged]

### ISSUE THREAD

**Issue by kratsg** [histfitter/histfitter#61]
In GitLab by @longjon on Jun 22, 2020, 08:46

_Merges multiplexContourPlot -> master_

I've added an option to produce a plot highlighting where each input SR is used in the final expected contour (--plotUsedContours), example: [usedExpectedContours_old.pdf](/uploads/918ec7cc1f12d490152ea19f61eee1e8/usedExpectedContours_old.pdf).  I've also updated the main part of the script to be more accurate and robust in complicated overlaps with a lot of sliced up subregions.  

tagging: @jlorenz and @pataraia for merging cc: @lawrenceleejr

**Comment by kratsg** [comment]
In GitLab by @llongo on Jun 23, 2020, 03:22

Hi @longjon ,
I see a couple of white area between the blue and green area; are these not covered by both SRs and should we expect an hole? If so, I think it's not highlighted by the final contour.
Are you aware of what Giordon has reported in this [issue#8](https://gitlab.cern.ch/HistFitter/HistFitter/-/issues/8) ?
Thanks,
Luigi

**Comment by kratsg** [comment]
In GitLab by @longjon on Jun 23, 2020, 05:01

Hi @llongo, I think those are just artifacts of how the sliced regions are assigned to the signal regions.  It's not a hole in the coverage.  This is really just meant to highlight which sliced up contours are from which SR as a sanity check.  That said, I'm still getting some undesirable results with a lot of input regions that I'm still looking into, so I may have further updates.

I had only quickly seen Giordon's issue.  Thanks, it's good to know the ordering might make a difference.

Cheers,
Jonathan

**Comment by kratsg** [comment]
In GitLab by @longjon on Jun 24, 2020, 06:17

added 1 commit

<ul><li>8aaa8dad - * Option to use Z-score based subRegion to SR.  This tends to be more accurate...</li></ul>

[Compare with previous version](/HistFitter/HistFitter/-/merge_requests/61/diffs?diff_id=591845&start_sha=36e70c7e6acd3d9e926eb703fbaaf62bc443f35f)

**Comment by kratsg** [comment]
In GitLab by @longjon on Jun 24, 2020, 06:25

@gstark I'm not sure if this would have any affect on your problems, but you could try using https://gitlab.cern.ch/longjon/HistFitter/-/blob/multiplexContourPlot/scripts/multiplexContours.py 
You should use this with --useZScoreAssociation (--plotUsedContours to see if the pieces look ok).  This has been behaving better for me when the contours get sliced up in complicated ways.  However, the uncertainty band can get broken.  I haven't had time to look at that yet--so that's will a WIP.

I started from a previous commit, so this doesn't have the convex hull calls on various polygons.

**Comment by kratsg** [comment]
In GitLab by @longjon on Jun 26, 2020, 09:12

added 3 commits

<ul><li>936814ba - * Adding options to turn on new features.</li><li>22ba42e5 - * Changes to make band look nice</li><li>4d29cc5c - More cleanup and fix for bad behavior where band was drawn over whole exclusion</li></ul>

[Compare with previous version](/HistFitter/HistFitter/-/merge_requests/61/diffs?diff_id=594154&start_sha=8aaa8dadc4472d2e0a0da56cf144a5dc0e3e28de)

**Comment by kratsg** [comment]
In GitLab by @longjon on Jun 26, 2020, 09:16

Ok, I've worked out all of the issues I had with my own contours.  I'm pretty happy with how this is working now.  It should be more robust when several regions are used and the overlaps are complex.  
![image](/uploads/3f8bd3cdd8ce4b5088319096ca34c9f4/image.png)

**Comment by kratsg** [comment]
In GitLab by @longjon on Jun 26, 2020, 13:37

added 1 commit

<ul><li>318e65b0 - Fix to argument</li></ul>

[Compare with previous version](/HistFitter/HistFitter/-/merge_requests/61/diffs?diff_id=594264&start_sha=4d29cc5c10eb1514945b4263d26bd28ac8249a6d)

**Comment by kratsg** [comment]
In GitLab by @longjon on Jun 26, 2020, 13:41

changed the description

**Comment by kratsg** [comment]
In GitLab by @longjon on Jun 26, 2020, 13:48

changed the description

**Comment by kratsg** [comment]
In GitLab by @gstark on Jun 26, 2020, 15:35

This is certainly working a lot better. My struggle is that I'm unable to stitch the three regions I have (I suspect because one looks like a giant hole but not sure).

![Screenshot_2020-06-26_17.07.54](/uploads/931ebe702cdaaadd1111a4b4d50977c0/Screenshot_2020-06-26_17.07.54.png)

The input contours are below, and I still expect less of a sharp dip around the 200-250 GeV / 10 GeV area as the combination should resolve it...

![Screenshot_2020-06-26_18.33.59](/uploads/489fb516f4016c20ba1155986d14698b/Screenshot_2020-06-26_18.33.59.png)

**Comment by kratsg** [comment]
In GitLab by @longjon on Jun 27, 2020, 02:47

added 2 commits

<ul><li>d95f3080 - * Changes to make band look nice</li><li>e116acba - Merge branch &#39;multiplexContourPlot&#39; of...</li></ul>

[Compare with previous version](/HistFitter/HistFitter/-/merge_requests/61/diffs?diff_id=594340&start_sha=318e65b08c43e7f3c1461e50b8631a4513bea23d)

**Comment by kratsg** [comment]
In GitLab by @longjon on Jun 28, 2020, 04:23

added 1 commit

<ul><li>808a896e - * Tweaks for problems seen in exp line with ewk comb inputs</li></ul>

[Compare with previous version](/HistFitter/HistFitter/-/merge_requests/61/diffs?diff_id=594517&start_sha=e116acba4dcae8afb9a0452dace82a9725802903)

**Comment by kratsg** [comment]
In GitLab by @longjon on Jun 28, 2020, 04:31

added 1 commit

<ul><li>d1e7c23b - * Update arguments and default</li></ul>

[Compare with previous version](/HistFitter/HistFitter/-/merge_requests/61/diffs?diff_id=594519&start_sha=808a896ef4e953bc8ebd03bcc6e1c0fcada3b7b9)

**Comment by kratsg** [comment]
In GitLab by @longjon on Jun 28, 2020, 04:32

@gstark can you see if it works for you, including the band, with this latest commit?

It looks ok for me ![image](/uploads/90c19539667cb5d0802a2dc721b9d3a6/image.png)

**Comment by kratsg** [comment]
In GitLab by @longjon on Jun 28, 2020, 04:33

changed the description

**Comment by kratsg** [comment]
In GitLab by @llongo on Jun 28, 2020, 09:59

Hi @longjon ,
I've tested your last [version](https://gitlab.cern.ch/longjon/HistFitter/-/blob/multiplexContourPlot/scripts/multiplexContours.py) on my contours and it seems working very nice. Here an example
![image](/uploads/237ac2c082cfa0a7257f8c5c48b6560e/image.png)

Just one small comment; at the beginning, I've stumbled on this error 
> Traceback (most recent call last):
  File "../scripts/multiplexContours_Merge61.py", line 536, in <module>
    bestRegions, expCurve = main()
  File "../scripts/multiplexContours_Merge61.py", line 122, in main
    cs = ax.contour(x,y,z1-z2, ":", levels=[0] ) # this creates contours where the two surfaces have the same Z value
ValueError: operands could not be broadcast together with shapes (500,200) (100,75)

and I've realized it is due to the different dimensions and ranges I've for the 2 contours. Could it be possible to add a check on this? What do you think? Thanks

**Comment by kratsg** [comment]
In GitLab by @longjon on Jun 28, 2020, 12:06

@llongo do I understand correctly that you used different x and y ranges in harvestToContours.py for the inputs?  I didn't change this part of the code so you'd have the same issue with the current code.  Maybe you have an idea how to check that.

**Comment by kratsg** [comment]
In GitLab by @llongo on Jun 28, 2020, 14:39

@longjon , yes I used different x and y ranges and also resolutions. I suspect we need to check both to be sure about the stitching of the contours. I'll look for a way to check these.

**Comment by kratsg** [comment]
In GitLab by @gstark on Jun 29, 2020, 06:31

![Screenshot_2020-06-29_09.29.37](/uploads/d8797757a8414c7853bccb10395b827c/Screenshot_2020-06-29_09.29.37.png)

looks like it's now successfully including the contour. (Compare to this version: https://gitlab.cern.ch/HistFitter/HistFitter/-/merge_requests/61#note_3581079).

**Comment by kratsg** [comment]
In GitLab by @gstark on Jun 29, 2020, 06:33

However, the observed limit is rather off (amongst other things):

![Screenshot_2020-06-29_09.32.36](/uploads/923a51d05cc8b904b40eaf3723459ffe/Screenshot_2020-06-29_09.32.36.png)

**Comment by kratsg** [comment]
In GitLab by @longjon on Jun 29, 2020, 06:44

added 1 commit

<ul><li>173f7a7e - Add check on multiplex input files</li></ul>

[Compare with previous version](/HistFitter/HistFitter/-/merge_requests/61/diffs?diff_id=595057&start_sha=d1e7c23b87c47d04103a08c90b135e72ea6a99b5)

**Comment by kratsg** [comment]
In GitLab by @longjon on Jun 29, 2020, 06:45

added 1 commit

<ul><li>a6c56e1a - Missing exit()</li></ul>

[Compare with previous version](/HistFitter/HistFitter/-/merge_requests/61/diffs?diff_id=595059&start_sha=173f7a7e9271f2befaeb12532e0170987b4e554b)

**Comment by kratsg** [comment]
In GitLab by @longjon on Jun 29, 2020, 06:45

@llongo Can you try what I just pushed on your files--it should?  I need to check some behavior with one of my contours so I tried a quick check on the input x,y grid.

**Comment by kratsg** [comment]
In GitLab by @longjon on Jun 29, 2020, 07:21

added 1 commit

<ul><li>ed855e55 - Deal with floating point precision for input check in multiplexContours.py</li></ul>

[Compare with previous version](/HistFitter/HistFitter/-/merge_requests/61/diffs?diff_id=595097&start_sha=a6c56e1ab09d6f784a61ee97353ae97de1b4f081)

**Comment by kratsg** [comment]
In GitLab by @llongo on Jun 30, 2020, 08:24

@longjon , unfortunately it was still crashing because there were 2 matrices of different size as input for numpy and because in [these lines](https://gitlab.cern.ch/longjon/HistFitter/-/blob/multiplexContourPlot/scripts/multiplexContours.py#L114-122) the check is done on the same object at the beginning of the loop. I've modified these lines like the following:

>     print (">>> Creating iso expected contours for all pairwise combinations of SRs")



    # Loop over combinations of input files and grab coordinates from surfances in pkl files
    for (region1, region2) in itertools.combinations(listOfInputFiles, 2):

        print(region1,region2)
        x,y = dict_Surfaces[region1]["x"], dict_Surfaces[region1]["y"]

        # Used to check that regions have same grid
        x_ref = dict_Surfaces[region2]['x']
        y_ref = dict_Surfaces[region2]['y']


        # Input checks
        if len(x) == len(x_ref) and len(y) == len(y_ref):
           if len(x)>0 and len(y)>0:
              if len(x[0]) == len(x_ref[0]) and len(y[0]) == len(y_ref[0]):
                if ( np.isclose(x_ref,x).all() and np.isclose(y_ref,y).all() ):
                 z1,z2 = dict_Surfaces[region1]["z"], dict_Surfaces[region2]["z"]
                 cs = ax.contour(x,y,z1-z2, ":", levels=[0] ) # this creates contours where the two surfaces have the same Z value

                 isoExpectedContours[(region1,region2)] = cs.allsegs[0] # grab list of arrays of coords of intersection contour
                else:
                 if not np.isclose(x_ref,x).all():
                    print ("X for %s from: %f to %f" % (region1, x[0][0],y[-1][0]))
                    print ("X for %s from: %f to %f" % (region2, x_ref[0][0],x_ref[-1][0]))
                 if not np.isclose(y_ref,y).all():
                    print ("Y for %s from: %f to %f" % (region1, y[0][0],y[-1][0]))
                    print ("Y for %s from: %f to %f" % (region2, y_ref[0][0],y_ref[-1][0]))

                 print(">>> Error, inputs are not close.  %s is different"%(region1))
                 sys.exit(1)

              else:
                 print(">>> Error, inputs must use same x and y limits and resolution in harvest contours.  %s is different"%(region1))
                 sys.exit(1)



So now the comparison is done only if the matrices size is the same. In this way I've also discovered another issues on going on my test relative to the fact the Y values stored in the pkl are different for the 2 contours even if in harvest.py I've set the same range; this means that this [step](https://gitlab.cern.ch/longjon/HistFitter/-/blob/multiplexContourPlot/scripts/multiplexContours.py#L130) is not correct for me because I'm not comparing the same point. Could you check with the changes above and let me know if it works smoothly for you?

**Comment by kratsg** [comment]
In GitLab by @longjon on Jun 30, 2020, 11:00

@llongo thanks for the more thorough check.  I tested it in one of my regions and it worked fine.  I can push this to this MR if you want.

@gstark with the above input checks, I see that the files you gave me from the combination limits you're trying to merge don't pass this check.  Are the inputs here https://gitlab.cern.ch/HistFitter/HistFitter/-/merge_requests/61#note_3584143 different than what you sent me to try before?

**Comment by kratsg** [comment]
In GitLab by @gstark on Jun 30, 2020, 11:03

I'm attaching the tarball of the input contours for posterity.

[combinatino.tar.gz](/uploads/904eca7ce7d2e38818cdc09da6f1065d/combinatino.tar.gz)

![Screenshot_2020-06-30_14.02.41](/uploads/4b48849d14bfb008309fb9140cb210d4/Screenshot_2020-06-30_14.02.41.png)
![Screenshot_2020-06-30_14.02.46](/uploads/3bead169992be51fe6b472107261fdd6/Screenshot_2020-06-30_14.02.46.png)
![Screenshot_2020-06-30_14.02.51](/uploads/a1334d939e9b6f29b15bc18769ad6daa/Screenshot_2020-06-30_14.02.51.png)

**Comment by kratsg** [comment]
In GitLab by @llongo on Jun 30, 2020, 16:19

@longjon , you can include them in your MR. Thanks

**Comment by kratsg** [comment]
In GitLab by @longjon on Jul 1, 2020, 08:50

added 1 commit

<ul><li>5e605817 - * Better input checking to ensure the iterpratations are done on the same grid by @llongo</li></ul>

[Compare with previous version](/HistFitter/HistFitter/-/merge_requests/61/diffs?diff_id=597213&start_sha=ed855e55e7f4d1cdadf1f908a91bee08afaaea91)

**Comment by kratsg** [comment]
In GitLab by @longjon on Jul 1, 2020, 09:03

Hi @gstark, is it possible to get these three inputs with the same interpretation grid?  y/x limits and resolution?  This probably explains your order dependence from before as it picked the x/y from the first sample, so the ranges would be different depending on the order.

If I ignore that for now, part of the problem is likely due to this input contour ![image](/uploads/021df25113ce6b6191e6bd5b28d22f38/image.png) covering such a small area, while according to your plot it has exclusion power at lower masses.  If it is picked as the best SR in some low mass area, there is no overlap between this input contour (polygon) it.

Finally, I tweaked things to, as much as possible, assign SRs only if they're within the input expected contour.  This is instead of just using the interpolated surface.  This works better for the inputs Giordon sent.  However, you can see how the issues from above will affect the band, which will be from the red region inside the Exp and blue outside.
![image](/uploads/6eb6ebf591c0736bfb5c6595b1a31d55/image.png)

This all appears to still be working for my own contours; though I haven't had time to try all of them yet.

**Comment by kratsg** [comment]
In GitLab by @gstark on Jul 1, 2020, 09:07

> is it possible to get these three inputs with the same interpretation grid? y/x limits and resolution?

All contour are made with the same script -- but they have varying number of points included:

```
GROUP=combination harvestToContours.py -i harvest_${GROUP}.json -o harvest_${GROUP}.root -x mn2 -y dm --xMin 50 --xMax 400 --yMin 0 --yMax 1000 --forbiddenFunction 'None'
```

As you can see, I'm seeing the same xmin/xmax/ymin/ymax here. Is there anything more I can do to keep the limits/resolution the same?

**Comment by kratsg** [comment]
In GitLab by @longjon on Jul 1, 2020, 09:10

I'm not familar with what goes on in harvestToContours.  I would have assumed that is enough.  I would try asking Larry if you don't see anything obvious in there.

**Comment by kratsg** [comment]
In GitLab by @gstark on Jul 1, 2020, 09:14

@lawrenceleejr -- sorry to bother you yet again. How do we get inputs to multiplexContour compatible so that we don't see strange behavior like in #8.

**Comment by kratsg** [comment]
In GitLab by @llongo on Jul 1, 2020, 09:51

I've the same issue with harvestToContours.py; Min and Max are different from what I've set

**Comment by kratsg** [comment]
In GitLab by @longjon on Jul 1, 2020, 14:22

added 1 commit

<ul><li>1d548461 - Add option to remove small subRegions, these were causing crash in cascade_union</li></ul>

[Compare with previous version](/HistFitter/HistFitter/-/merge_requests/61/diffs?diff_id=597366&start_sha=5e6058172b3b7c6a0ba73b3e199753e30bcdc200)

**Comment by kratsg** [comment]
In GitLab by @llongo on Jul 19, 2020, 10:10

Hi, 
I believe we can close this merge request since the issue observed is related to harvestToContours.py and not to multiplexContours.py.
Cheers,
Luigi

**Comment by kratsg** [comment]
In GitLab by @llongo on Jul 19, 2020, 10:10

merged

**Comment by kratsg** [comment]
In GitLab by @llongo on Jul 19, 2020, 10:10

mentioned in commit 895433c48656e2da79c6e0e0b66034e65c5ce0eb
