### ISSUE TITLE
Issue with contourPlotter

### ISSUE THREAD

**Issue by ericballabene** [histfitter/histfitter#76]
Hi, 
I've started to use python3 and v1.0.0. I got into this:

```pytb
Traceback (most recent call last):
  File "/users2/ballaben/c1c1-ww-hf/utils/Contour/contourPlotterExample.py", line 13, in <module>
    import contourPlotter
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_98python3_ATLAS_1/x86_64-centos7-gcc8-opt/lib/ROOT/_facade.py", line 121, in _importhook
    return _orig_ihook(name, *args, **kwds)
  File "/users2/ballaben/HistFitter/scripts/contourPlotter.py", line 30
    self.figLabel = "#it{Example Label}"
                                       ^
TabError: inconsistent use of tabs and spaces in indentation
```

Cheers,
Eric

**Comment by matthewfeickert** [comment]
@ericballabene Once PR #77 is merged you should be able to just use the `HEAD` of `master`. Though if you want to try something now, you can try using the branch that PR #77 is based on (that would actually be a good test).

**Comment by matthewfeickert** [comment]
@ericballabene Please try again using the `HEAD` of `master`.

**Comment by ericballabene** [comment]
it worked @matthewfeickert , thanks!
