### ISSUE TITLE
Error in harvestToContours.py with python3

### ISSUE THREAD

**Issue by ericballabene** [histfitter/histfitter#80]
Hi, 
I'm using python 3 and head master. I'm getting this:

```console
[ericballabene]$ harvestToContours.py -i json/combined_hypotest__1_harvest_list.json -x m0 -y m12 -l None --xMin 100 --xMax 250 --yMin 1 --yMax 150 --xResolution 25 --yResolution 10
```

```pytb
Interpolating surface
Traceback (most recent call last):
  File "/users2/ballaben/histfitter_v1.0.0/scripts/harvestToContours.py", line 859, in <module>
    main()
  File "/users2/ballaben/histfitter_v1.0.0/scripts/harvestToContours.py", line 154, in main
    processInputFile(inputFile = args.inputFile, outputFile = f, label = "")
  File "/users2/ballaben/histfitter_v1.0.0/scripts/harvestToContours.py", line 249, in processInputFile
    outputGraphs = interpolateSurface( resultsDict , args.interpolation , args.useROOT , outputSurface=True if label=="" else False)
  File "/users2/ballaben/histfitter_v1.0.0/scripts/harvestToContours.py", line 494, in interpolateSurface
    x0 =   list( zip( *modelPoints )[0] )
TypeError: 'zip' object is not subscriptable
```

Cheers,
Eric

**Comment by matthewfeickert** [comment]
https://stackoverflow.com/a/27431433/8931942

> In Python 2, zip returned a list. In Python 3, zip returns an iterable object.

so

https://github.com/histfitter/histfitter/blob/1dbb446c79c9f1bc65365d38a21c032741a8e181/scripts/harvestToContours.py#L494-L495

should (probably) be

```python
 x0, y0 = list(zip(*modelPoints))[:2]
```

**Comment by ericballabene** [comment]
Thanks, now I have:

Traceback (most recent call last):
  File "/users2/ballaben/histfitter_v1.0.0/scripts/harvestToContours.py", line 860, in <module>
    main()
  File "/users2/ballaben/histfitter_v1.0.0/scripts/harvestToContours.py", line 154, in main
    processInputFile(inputFile = args.inputFile, outputFile = f, label = "")
  File "/users2/ballaben/histfitter_v1.0.0/scripts/harvestToContours.py", line 249, in processInputFile
    outputGraphs = interpolateSurface( resultsDict , args.interpolation , args.useROOT , outputSurface=True if label=="" else False)
  File "/users2/ballaben/histfitter_v1.0.0/scripts/harvestToContours.py", line 630, in interpolateSurface
    pickle.dump({"x": xymeshgrid[0], "y": xymeshgrid[1],"z": ZI} ,outfile, pickle.HIGHEST_PROTOCOL)
TypeError: write() argument must be str, not bytes

**Comment by matthewfeickert** [comment]
In 

https://github.com/histfitter/histfitter/blob/1dbb446c79c9f1bc65365d38a21c032741a8e181/scripts/harvestToContours.py#L624-L630

`outfile` has been opened with `'w'`, but `pickle` is a binary serialization and so these should be `wb`.

```
Help on built-in function open in module io:

open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)
    Open file and return a stream.  Raise OSError upon failure.
    
    file is either a text or byte string giving the name (and the path
    if the file isn't in the current working directory) of the file to
    be opened or an integer file descriptor of the file to be
    wrapped. (If a file descriptor is given, it is closed when the
    returned I/O object is closed, unless closefd is set to False.)
    
    mode is an optional string that specifies the mode in which the file
    is opened. It defaults to 'r' which means open for reading in text
    mode.  Other common values are 'w' for writing (truncating the file if
    it already exists), 'x' for creating and writing to a new file, and
    'a' for appending (which on some Unix systems, means that all writes
    append to the end of the file regardless of the current seek position).
    In text mode, if encoding is not specified the encoding used is platform
    dependent: locale.getpreferredencoding(False) is called to get the
    current locale encoding. (For reading and writing raw bytes use binary
    mode and leave encoding unspecified.) The available modes are:
    
    ========= ===============================================================
    Character Meaning
    --------- ---------------------------------------------------------------
    'r'       open for reading (default)
    'w'       open for writing, truncating the file first
    'x'       create a new file and open it for writing
    'a'       open for writing, appending to the end of the file if it exists
    'b'       binary mode
    't'       text mode (default)
    '+'       open a disk file for updating (reading and writing)
    'U'       universal newline mode (deprecated)
    ========= ===============================================================

```

so should just need to go from `'w'` -> `'wb'`:

```python
     with open(args.outputFile+'.expectedSurface.pkl', 'wb') as outfile: 
         pickle.dump({"x": xymeshgrid[0], "y": xymeshgrid[1],"z": ZI} ,outfile, pickle.HIGHEST_PROTOCOL) 
 elif whichContour==observedContour and outputSurface: 
     print (">>> ... ... Writing out observed surface to pickle file") 
     with open(args.outputFile+'.observedSurface.pkl', 'wb') as outfile: 
         pickle.dump({"x": xymeshgrid[0], "y": xymeshgrid[1],"z": ZI} ,outfile, pickle.HIGHEST_PROTOCOL)
```
